export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const ROLE_REPOSITORY = Symbol('ROLE_REPOSITORY');
export const ROLE_PERMISSION_REPOSITORY = Symbol('ROLE_PERMISSION_REPOSITORY');

export enum RoleName {
    ADMIN = 'admin',
    CLIENT = 'client',
}

export enum Permission {
    AUTH_REFRESH = 'AUTH_REFRESH',
    LOGOUT = 'LOGOUT',

    WHO_AM_I = 'WHO_AM_I',
    USER_GET = 'USER_GET',
    USER_LIST = 'USER_LIST',

    ACCOUNT_GET = 'ACCOUNT_GET',
    ACCOUNT_LIST = 'ACCOUNT_LIST',
    ACCOUNT_CREATE = 'ACCOUNT_CREATE',
    ACCOUNT_UPDATE = 'ACCOUNT_UPDATE',
    ACCOUNT_DEACTIVATE = 'ACCOUNT_DEACTIVATE',
    ACCOUNT_ACTIVATE = 'ACCOUNT_ACTIVATE',
    ACCOUNT_BLOCK = 'ACCOUNT_BLOCK',
    ACCOUNT_UNBLOCK = 'ACCOUNT_UNBLOCK',

    ACCOUNT_DEPOSIT_GET = 'ACCOUNT_DEPOSIT_GET',
    ACCOUNT_DEPOSIT_LIST = 'ACCOUNT_DEPOSIT_LIST',
    ACCOUNT_DEPOSIT_CREATE = 'ACCOUNT_DEPOSIT_CREATE',

    ACCOUNT_TRANSFER_GET = 'ACCOUNT_TRANSFER_GET',
    ACCOUNT_TRANSFER_LIST = 'ACCOUNT_TRANSFER_LIST',
    ACCOUNT_TRANSFER_CREATE = 'ACCOUNT_TRANSFER_CREATE',
    ACCOUNT_TRANSFER_CANCEL = 'ACCOUNT_TRANSFER_CANCEL',

    DEPOSIT_GET = 'DEPOSIT_GET',
    DEPOSIT_LIST = 'DEPOSIT_LIST',
    DEPOSIT_CANCEL = 'DEPOSIT_CANCEL',

    TRANSFER_GET = 'TRANSFER_GET',
    TRANSFER_LIST = 'TRANSFER_LIST',
    TRANSFER_CANCEL = 'TRANSFER_CANCEL',
}